# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub_dlg_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(235, 273)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit_energy = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_energy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_energy.setObjectName("lineEdit_energy")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_energy)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_quad = QtWidgets.QGroupBox(Dialog)
        self.groupBox_quad.setObjectName("groupBox_quad")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_quad)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_quad)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_quadL = QtWidgets.QLineEdit(self.groupBox_quad)
        self.lineEdit_quadL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_quadL.setObjectName("lineEdit_quadL")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_quadL)
        self.label_3 = QtWidgets.QLabel(self.groupBox_quad)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_quadLd = QtWidgets.QLineEdit(self.groupBox_quad)
        self.lineEdit_quadLd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_quadLd.setObjectName("lineEdit_quadLd")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_quadLd)
        self.verticalLayout.addWidget(self.groupBox_quad)
        self.groupBox_sole = QtWidgets.QGroupBox(Dialog)
        self.groupBox_sole.setEnabled(False)
        self.groupBox_sole.setObjectName("groupBox_sole")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_sole)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox_sole)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_soleL = QtWidgets.QLineEdit(self.groupBox_sole)
        self.lineEdit_soleL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_soleL.setObjectName("lineEdit_soleL")
        self.gridLayout.addWidget(self.lineEdit_soleL, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_sole)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_soleLd = QtWidgets.QLineEdit(self.groupBox_sole)
        self.lineEdit_soleLd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_soleLd.setObjectName("lineEdit_soleLd")
        self.gridLayout.addWidget(self.lineEdit_soleLd, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_sole)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "束流参数"))
        self.label.setText(_translate("Dialog", "束流能量E(MeV)"))
        self.lineEdit_energy.setText(_translate("Dialog", "53.4"))
        self.groupBox_quad.setTitle(_translate("Dialog", "四极铁参数"))
        self.label_2.setText(_translate("Dialog", "透镜(Q铁)有效长度L(m)"))
        self.lineEdit_quadL.setText(_translate("Dialog", "0.1"))
        self.label_3.setText(_translate("Dialog", "漂移段长度(Ld)(m)"))
        self.lineEdit_quadLd.setText(_translate("Dialog", "1.4528"))
        self.groupBox_sole.setTitle(_translate("Dialog", "螺线管参数"))
        self.label_4.setText(_translate("Dialog", "线圈有效长度L(m)"))
        self.lineEdit_soleL.setText(_translate("Dialog", "0.1"))
        self.label_5.setText(_translate("Dialog", "漂移段长度Ld(m)"))
        self.lineEdit_soleLd.setText(_translate("Dialog", "1.4528"))
        self.pushButton.setText(_translate("Dialog", "保存"))
